#!/bin/sh
HARDWARE_MODEL=`grep Hardware /proc/cpuinfo | awk "{print \\$3}"`
/bin/echo "Hardware Model=${HARDWARE_MODEL}"

case $HARDWARE_MODEL in
		"SLP_PQ")	/bin/echo "This is PQ"
			/usr/sbin/wpa_supplicant -u -t -B -ddd -f /var/log/wpa_supplicant.log
		;;
		"U1SLP" | "U1HD")	/bin/echo "This is U1SLP"
			/usr/sbin/wpa_supplicant -Dwext -u -t -B -ddd -f /var/log/wpa_supplicant.log
		;;
		"SLP7_C210")	/bin/echo "This is C210"
			/usr/sbin/wpa_supplicant -Dwext -u -t -B -ddd -f /var/log/wpa_supplicant.log
		;;
		"SLP10_C210")
			/usr/sbin/wpa_supplicant -Dwext -u -t -B -ddd -f /var/log/wpa_supplicant.log
		;;
		*)
			/usr/sbin/wpa_supplicant -u -t -B -ddd -f /var/log/wpa_supplicant.log
		;;
esac
